In [31]:
import numpy as np
import pandas as pd
poplar_annots = pd.read_csv('Ptrichocarpa_444_v3.1.annotation_info.txt', sep='\t')
poplar_annots.head()

,#pacId,locusName,transcriptName,peptideName,Pfam,Panther,KOG,ec,KO,GO,Best-hit-arabi-name,arabi-symbol,arabi-defline
0,37275604,Potri.001G000200,Potri.001G000200.1,Potri.001G000200.1.p,PF14111,"PTHR31286,PTHR31286:SF2",NaN,"3.5.1.28,3.2.1.96",NaN,NaN,AT2G01050.1,NaN,zinc ion binding;nucleic acid binding
1,37273386,Potri.001G000300,Potri.001G000300.1,Potri.001G000300.1.p,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,37280376,Potri.001G000400,Potri.001G000400.1,Potri.001G000400.1.p,PF11779,PTHR33727,NaN,NaN,NaN,NaN,AT2G30942.1,NaN,Protein of unknown function (DUF3317)
3,37280379,Potri.001G000400,Potri.001G000400.2,Potri.001G000400.2.p,PF11779,PTHR33727,NaN,NaN,NaN,NaN,AT2G30942.1,NaN,Protein of unknown function (DUF3317)
4,37280377,Potri.001G000400,Potri.001G000400.3,Potri.001G000400.3.p,PF11779,PTHR33727,NaN,NaN,NaN,NaN,AT2G30942.1,NaN,Protein of unknown function (DUF3317)

In [5]:
names = ["Vocabulary", "Term", "Definition"]
go_annots = pd.read_csv('GO.terms.txt', sep = "\t", names= names)
go_annots.head()

  Vocabulary        Term                        Definition
0         GO  GO:0008150                biological_process
1         GO  GO:0048311        mitochondrion distribution
2         GO  GO:0000003                      reproduction
3         GO  GO:0000001         mitochondrion inheritance
4         GO  GO:0000002  mitochondrial genome maintenance

In [10]:
simple_poplar_annots = poplar_annots.iloc[:,[3,9]]
simple_poplar_annots.head()

            peptideName   GO
0  Potri.001G000200.1.p  NaN
1  Potri.001G000300.1.p  NaN
2  Potri.001G000400.1.p  NaN
3  Potri.001G000400.2.p  NaN
4  Potri.001G000400.3.p  NaN

In [42]:
simple_poplar_annots=simple_poplar_annots.dropna(axis=0, how='any')
simple_poplar_annots.head()

             peptideName                                                 GO
6   Potri.001G000500.1.p                   GO:0055114,GO:0016491,GO:0005507
7   Potri.001G000600.1.p                   GO:0055114,GO:0016491,GO:0005507
9   Potri.001G000800.1.p  GO:0008017,GO:0007018,GO:0005524,GO:0003777,GO...
19  Potri.001G001500.1.p                              GO:0008270,GO:0005515
20  Potri.001G001500.2.p                              GO:0008270,GO:0005515

In [44]:
go_dfs = []
for index, row in simple_poplar_annots.iterrows():
    terms = row.GO.split(',')
    peptide = np.repeat(row.peptideName, len(terms))
    single=pd.DataFrame(terms,peptide)
    go_dfs.append(single)

                               0
Potri.001G000500.1.p  GO:0055114
Potri.001G000500.1.p  GO:0016491
Potri.001G000500.1.p  GO:0005507

In [45]:
print(go_dfs[0])

                               0
Potri.001G000500.1.p  GO:0055114
Potri.001G000500.1.p  GO:0016491
Potri.001G000500.1.p  GO:0005507

In [56]:
whole_poplar = pd.concat(go_dfs)

In [58]:

whole_poplar.head()

                               0
Potri.001G000500.1.p  GO:0055114
Potri.001G000500.1.p  GO:0016491
Potri.001G000500.1.p  GO:0005507
Potri.001G000600.1.p  GO:0055114
Potri.001G000600.1.p  GO:0016491